kubectl create clusterrole convalkon-role --verb=get --resource=deployments,configmaps

openssl req -new -x509 -subj "/CN=convalkon.default.svc"  -addext "subjectAltName = DNS:convalkon.default.svc" -nodes -newkey rsa:4096 -keyout tls.key -out tls.crt -days 365